services:
  app:
    image: gcr.io/eyego-mvp/api:latest
    container_name: backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      - kafka

  frontend:
    image: gcr.io/eyego-mvp/frontend:latest
    container_name: frontend
    ports:
      - "8082:8081"
    networks:
      - app_network
    restart: unless-stopped

  websocket:
    image: gcr.io/eyego-mvp/ws:latest
    container_name: websocket
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - app_network

  notification-service:
    image: gcr.io/eyego-mvp/notfication:latest
    container_name: notification-service
    build: .
    ports:
      - "8083:8083"
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGODB_URI=mongodb+srv://
    networks:
      - app_network
    depends_on:
      - kafka
      - zookeeper
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app_network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 
      KAFKA_ADVERTISED_LISTENERS: 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 
      KAFKA_LISTENERS: 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./eyego/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./eyego/certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./eyego/certs/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - app
      - frontend
      - websocket
      - notification-service
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
